### ISSUE TITLE
LU310.COM strange behavior

### ISSUE THREAD

**Issue by eightbitswide** [nihirash/ZINC#11]
The LU310.COM program for extracting .LBR files works, but requires you to keep the Enter key pressed for repeated keystrokes until it is finished.  Example:  LU -O LU101.LBR -L -E LU.DZC

**Comment by nihirash** [comment]
Are this issue can be reproduced in other releases?

**Comment by eightbitswide** [comment]
I've reproduced it in the official release, not the "experimental" UART version.  I've not tried it with that one.

**Comment by nihirash** [comment]
[zinc.zip](https://github.com/user-attachments/files/15858984/zinc.zip)

Try with this version - this fix should be included in next release

**Comment by nihirash** [comment]
Should be fixed with https://github.com/nihirash/ZINC/releases/tag/2024.06.16

**Comment by eightbitswide** [comment]
LU310.COM appears to be running nicely now.  I'm closing this issue.
