### ISSUE TITLE
Word Star 3.0 no longer saving Doc/Non Doc Files

### ISSUE THREAD

**Issue by eightbitswide** [nihirash/ZINC#12]
WordStar 3.0 is not longer saving DOC or NON DOC files.

**Comment by nihirash** [comment]
Very strange - cause I didn't change anything that should be linked to file operations.

Please send me distro of wordstar that you're using for tests(you can send it here - or in discord/directly to email)

**Comment by nihirash** [comment]
I've found Wordstar distro and bug can be reproduced.

**Comment by nihirash** [comment]
Please check this version:  [zinc.zip](https://github.com/user-attachments/files/15876954/zinc.zip)

**Comment by eightbitswide** [comment]
Initial test with a non document file and a few lines seems to show it working correctly.   I'll complete a two page phlog entry with Wordstar for the gopher site and give it a real shakedown soon.  If it can do that, I'll close this issue.

**Comment by eightbitswide** [comment]
Two page phlog entry created with WordStar 3.0 under the current release of ZINC without errors.   Closing this issue as resolved and tested.
