### ISSUE TITLE
Text Scrolling issue (right to left) Supercalc

### ISSUE THREAD

**Issue by eightbitswide** [nihirash/ZINC#14]
Noticed right to left scrolling issue in Supercalc.  Last two columns sticking when scrolling a large spreadsheet.

To reproduce this issue:   filename: scalc106.zip (File located in CP/M section of agon.gunstar.one)
( or http://www.retroarchive.org/maslin/disks/cpmprog/scalc106.zip)

(Using MODE 3 to run ZINC applications)

Install using H. Lear Siegler --> 1. Adm 3A
(All other defaults kept the same.)

In SC (supercalc) load the example "balance" using: / L balance A
Using the arrow keys, scroll to the left past "Jun" paying attention to the numbers under it.

**Comment by nihirash** [comment]
It's issue of this specific version of SuperCalc. 

I've got no similar issues with this version(after installation): https://github.com/rlauzon54/Kaypro-4-83/tree/main/Apps/supcalc2

**Comment by eightbitswide** [comment]
Considering this a non-ZINC issue and closing the issue.
