### ISSUE TITLE
Request: A way to access VDU output commands

### ISSUE THREAD

**Issue by eightbitswide** [nihirash/ZINC#6]
Would appreciate even basic access to VDU output commands for color, mode, plot, character redefine, and cls.   Perhaps a character sequence before the actual command could be inserted in the output?

Thank you for your efforts on this!

**Comment by nihirash** [comment]
Should be fixed with https://github.com/nihirash/ZINC/pull/7

For enabling and disabling terminal emulation use 27, 255 character sequence.

**Comment by nihirash** [comment]
Check latest release - it should implement required functions
